### ISSUE TITLE
travis 배포 에러

### ISSUE THREAD

**Issue by SuperRPM** [SuperRPM/springboot-project#1]
travis 로그
<img width="1043" alt="스크린샷 2022-03-23 오후 7 44 28" src="https://user-images.githubusercontent.com/71825628/159682146-791c35e3-922e-4886-9172-0a0022279b06.png">

view config에서 나온 메시지
<img width="1081" alt="스크린샷 2022-03-23 오후 7 45 30" src="https://user-images.githubusercontent.com/71825628/159682294-cc677b39-dc23-4f74-a7f8-99d085cca6f7.png">
위에 메시지중 세모표시된 경고는 수정했는데 오히려 배포가 더 진행이 안되서 다시 수정하기전으로 돌려서 새로 커밋했음.

AWS codedeploy
<img width="1099" alt="스크린샷 2022-03-23 오후 7 47 11" src="https://user-images.githubusercontent.com/71825628/159683420-7ed74f9e-c2cf-4f76-a992-65771f4bf6e5.png">

codedeploy-agent.log 에서 나온 메시지
<img width="1213" alt="스크린샷 2022-03-23 오후 7 50 55" src="https://user-images.githubusercontent.com/71825628/159683449-b5f7803f-71fc-45e8-9077-7cc56d5799ca.png">

github에 올리면 travis에서 CI를 진행하고 그걸 AWS S3로 보내주고 S3로 보내진 코드가 AWS codedeploy로 보내져서 마지막으로 '배포'가 된다고 이해하고 있음.

문제 해결이 어려운 이유가
travis에서 막혔으니까 travis에서 해결하면 될거같은데 failed to deploy라고만 나와서 뭐가 문제라는건지 잘 이해가안됨.

<details markdown="1">
<summary>.travis.yml</summary>

```yaml
language: java

jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - vidafirmar@gmail.com

before_deploy:
  - zip -r rpm-springboot-project *
  - mkdir -p deploy
  - mv rpm-springboot-project.zip deploy/rpm-springboot-project.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY

    secret_access_key: $AWS_SECRET_KEY

    bucket: rpm-spring-boot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: rpm-spring-boot-build
    key: rpm-springboot-project.zip

    bundle_type: zip
    application: rpm-spring-boot-project
    deployment_group: rpm-spring-boot-project-deploy-group
    region: ap-northeast-2
    wait-until-deployed: true
```

</details>

<details markdown="1">
<summary>.appspec.yml</summary>

```yaml
version: 0.0
os: linux
files:
  -source: /
   destination: /home/ec2-user/app/step2/zip/
   overwrite: yes
```

</details>
